name: app
type: php:7.2
build:
  flavor: composer
  caches:
    assets:
      watch:
        - "assets/sass/*.sass"
        - "gulpfile.js"
      directory: "public/css"
    # node_modules:
    #   # `watch` can degenerate to a single string.
    #   watch: "package-lock.json"
    # vendor:
    #   watch: "composer.*"


web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      index:
        - index.php
      allow: true
      headers:
        x-testing: "hello"


relationships:
  database: "mysqldb:mysql"
  solr: "solrsearch:solr"

#
mounts:
  "test-mount": "shared:files/test-mount"
disk: 2048
#
cron:
  job1:
    spec: "* * * * *"
    cmd: "echo $PATH"

# dependencies:
#   nodejs:
#     gulp-cli: "*"
hooks:
  build: |
    ls -la public/css
    if [ ! -f "public/css/blog.css" ]; then
      npm install -g gulp-cli
      npm install
      gulp
    fi
  deploy: |
    echo "This is the deploy hook firing!" 
  post_deploy: |
    echo "Post deploy"