name: app
type: php:7.2
build:
  flavor: composer

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      index:
        - index.php
      allow: true
      headers:
        x-testing: "hello"

    # "/info":
    #   root: "public"
    #   passthru: "/info.php"

    # "/submodule":
    #   root: "test-submodule/public"
    #   passthru: "/index.php"
    #   index:
    #     - index.php
    #   allow: true

relationships:
  database: "mysqldb:mysql"
  solr: "solrsearch:solr"

#
mounts:
  "test-mount": "shared:files/test-mount"
disk: 2048
#
cron:
  job1:
    spec: "* * * * *"
    cmd: "echo $PATH"

dependencies:
  nodejs:
    gulp-cli: "*"
hooks:
  build: |
    wget https://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.5.1.tar.gz
    tar xzvf ruby-2.5.1.tar.gz && cd ruby-2.5.1
    ./configure --prefix=/app/.global
    gem install sassc
    make && make install
    npm install
    gulp
    ls -l /mnt/cache
  deploy: |
    echo "This is the deploy hook firing!"
    if 
  post_deploy:
    echo "Post deploy"
