name: app
type: php:5.6
build:
  flavor: composer
disk: 2048
runtime:
  extensions:
    - mongo
  sizing_hints:
    request_memory: 1

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      index:
        - index.php
      allow: true
    # "/submodule":
    #   root: "test-submodule/public"
    #   passthru: "/index.php"
    #   index:
    #     - index.php
    #   allow: true

# relationships:
#   database: "mysqldb:mysql"
#   arbitrary: "solrsearch:solr"
# #
# mounts:
#   "test-mount": "shared:files/test-mount"
#
cron:
  job1:
    spec: "* * * * *"
    cmd: "echo $PATH"

hooks:
  build: |
    echo "This is the build hook firing!"
  deploy: |
    echo "This is the deploy hook firing!"