name: app
type: php:7.2
build:
  flavor: composer

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      index:
        - index.php
      allow: true
      headers:
        x-testing: "hello"

    # "/info":
    #   root: "public"
    #   passthru: "/info.php"

    # "/submodule":
    #   root: "test-submodule/public"
    #   passthru: "/index.php"
    #   index:
    #     - index.php
    #   allow: true

relationships:
  database: "mysqldb:mysql"
  solr: "solrsearch:solr"

#
mounts:
  "test-mount": "shared:files/test-mount"
disk: 2048
#
cron:
  job1:
    spec: "* * * * *"
    cmd: "echo $PATH"

dependencies:
  nodejs:
    gulp-cli: "*"
hooks:
  build: |
    export LIBRARY_PATH="/app/.global/lib"
    export LD_LIBRARY_PATH="/app/.global/lib"
    export PKG_CONFIG="/app/.global/lib/pkgconfig"
    wget http://libestr.adiscon.com/files/download/libestr-0.1.11.tar.gz
    tar xzvf libestr-0.1.11.tar.gz && cd libestr-0.1.11
    ./configure --prefix=/app/.global
    make && make install
    sleep 20
    cd ~
    wget http://www.rsyslog.com/files/download/rsyslog/rsyslog-8.39.0.tar.gz
    tar xzvf rsyslog-8.39.0.tar.gz && cd rsyslog-8.39.0
    ./configure --prefix=/app/.global LDFLAGS="-L/app/.global/lib"
    make && make install
    npm install
    gulp
  deploy: |
    echo "This is the deploy hook firing!"
  post_deploy:
    echo "Post deploy"


