name: app
type: php:7.1
build:
  flavor: composer
disk: 2048
dependencies:
  nodejs:
    gulp-cli: "*"
  ruby:
    sass: "*"

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      index:
        - index.php
      allow: true
      headers:
        x-testing: "hello"

    # "/submodule":
    #   root: "test-submodule/public"
    #   passthru: "/index.php"
    #   index:
    #     - index.php
    #   allow: true

# relationships:
#   database: "mysqldb:mysql"
#   solr: "solrsearch:solr"
#
# mounts:
#   "test-mount": "shared:files/test-mount"
#
cron:
  job1:
    spec: "* * * * *"
    cmd: "echo $PATH"

hooks:
  build: |
    npm install
    gulp
  deploy: |
    echo "This is the deploy hook firing!"

