name: app
type: php:5.6
build:
  flavor: composer
disk: 2048

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      index:
        - index.php
      allow: true
      headers:
        x-testing: "hello"
    "/info":
      root: "public"
      passthru: "/info.php"

    # "/submodule":
    #   root: "test-submodule/public"
    #   passthru: "/index.php"
    #   index:
    #     - index.php
    #   allow: true

relationships:
  database: "mysqldb:mysql"
  solr: "solrsearch:solr"
#
mounts:
  "test-mount": "shared:files/test-mount"
#
cron:
  job1:
    spec: "* * * * *"
    cmd: "echo $PATH"

dependencies:
  nodejs:
    gulp-cli: "*"
  ruby:
    sass: "*"
hooks:
  build: |
    npm install
    gulp
  deploy: |
    echo "This is the deploy hook firing!"