name: app
type: php:7.2
build:
  flavor: composer

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      index:
        - index.php
      allow: true
      headers:
        x-testing: "hello"

    # "/info":
    #   root: "public"
    #   passthru: "/info.php"

    # "/submodule":
    #   root: "test-submodule/public"
    #   passthru: "/index.php"
    #   index:
    #     - index.php
    #   allow: true

relationships:
  database: "mysqldb:mysql"
  solr: "solrsearch:solr"

#
mounts:
  "test-mount": "shared:files/test-mount"
disk: 2048
#
cron:
  job1:
    spec: "* * * * *"
    cmd: "echo $PATH"

dependencies:
  nodejs:
    gulp-cli: "*"
hooks:
  build: |
    npm install
    gulp
  deploy: |
    echo "This is the deploy hook firing!" 
  post_deploy: |
    echo "Post deploy"

build:
  caches:
    assets:
      watch:
        - "assets/sass/*.sass"

