mysqldb:
    type: mysql:10.0
    disk: 1024
    configuration:
        schemas:
            - main
            - other
        endpoints:
            admin:
                default_schema: main
                privileges:
                    main: admin
                    other: admin
solrsearch:
    type: solr:4.10
    disk: 512
rediscache:
    type: redis:3.0
